//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedtronicWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plano
    {
        public Plano()
        {
            this.Pins = new HashSet<Pin>();
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
        public byte[] img { get; set; }
    
        public virtual ICollection<Pin> Pins { get; set; }
    }
}
