//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedtronicWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Switch
    {
        public Switch()
        {
            this.PatchPanels = new HashSet<PatchPanel>();
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
        public string ip { get; set; }
        public string tipo { get; set; }
        public Nullable<byte> activo { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> patchPanel { get; set; }
    
        public virtual ICollection<PatchPanel> PatchPanels { get; set; }
        public virtual PatchPanel PatchPanel1 { get; set; }
    }
}
