//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedtronicWebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedtronicdbEntities : DbContext
    {
        public MedtronicdbEntities()
            : base("name=MedtronicdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PatchPanel> PatchPanels { get; set; }
        public DbSet<Pin> Pins { get; set; }
        public DbSet<Plano> Planoes { get; set; }
        public DbSet<Switch> Switches { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
    }
}
