//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedtronicWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatchPanel
    {
        public PatchPanel()
        {
            this.Switches = new HashSet<Switch>();
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
        public string ip { get; set; }
        public string tipo { get; set; }
        public Nullable<byte> activo { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> @switch { get; set; }
    
        public virtual Switch Switch1 { get; set; }
        public virtual ICollection<Switch> Switches { get; set; }
    }
}
