//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedtronicRestApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class medtronicdbEntities1 : DbContext
    {
        public medtronicdbEntities1()
            : base("name=medtronicdbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Nodo> Nodoes { get; set; }
        public virtual DbSet<Pin> Pins { get; set; }
        public virtual DbSet<Plano> Planoes { get; set; }
        public virtual DbSet<Switch> Switches { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
