//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedtronicRestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pin
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string x { get; set; }
        public string y { get; set; }
        public string patchIp { get; set; }
        public string switchIp { get; set; }
        public Nullable<int> plano { get; set; }
    
        public virtual Plano Plano1 { get; set; }
    }
}
